### ISSUE TITLE
IAP crashes sometimes on Android when doing buy directly after restore

### ISSUE THREAD

**Issue by subsoap** [defold/extension-iap#14] opened 2020-01-16 07:38 UTC
I do not have stacktrace / errors / logs at the moment.

This doesn't seem to happen if I add a timer.delay of 0.1 for the buy instead of making it directly after.

**Comment by subsoap** [comment] 2020-02-10 06:05
The way I have solved this in general I think is to remove everything I can from the callback functions.

https://github.com/subsoap/iap_manager this example is stable for me, and was used in live games without issue.

**Comment by britzl** [comment] 2020-02-10 07:32
I'd like to understand this error and fix it. Is it when I do:

```
iap.restore()
iap.buy("foobar")
```

**Comment by subsoap** [comment] 2020-02-10 10:33
I never got a small reproduction sample as I first tried to make the generalized iap_manager with broadcast and not using NEs directly in the callback. So should probably close this one until a sample can be provided. I did try to make a sample but it didn't crash, it's possible other wires were crossed.

**Comment by subsoap** [comment] 2020-02-10 10:34
What could be worth investigating is why other NEs tend to crash when they are called in IAP's callback.

**Comment by britzl** [comment] 2020-02-10 11:26
Can you provide an example of how I can get it to crash? Which other extension should I call from within the iap.buy or iap.list callback?

**Comment by subsoap** [comment] 2020-02-10 11:39
Try producing any kind of error in the callback first?

GameAnalytics was what I had crashing happening with before

https://github.com/GameAnalytics/GA-SDK-DEFOLD/archive/master.zip
https://github.com/GameAnalytics/defold-openssl/archive/master.zip

**Comment by britzl** [comment] 2020-02-11 06:34
You mean like this:

```
iap.set_listener(function()
    error("Foobar")
end)

iap.restore()
iap.buy("goldbars")
```

**Comment by britzl** [comment] 2020-03-09 10:44
Ping @subsoap . Do you have a solid repro case for this?

**Comment by subsoap** [comment] 2020-03-10 06:23
Something like this is what has crashed before. The problem is when errors happen in native extensions callbacks in general, not specific to this extension.

```
iap.set_listener(function()
    msg.post("does_not_exist", "crash_me")
end)
```

**Comment by AGulev** [comment] 2020-03-10 06:35
I think I made a fix for that some time ago
https://github.com/defold/extension-iap/commit/1a778d0e98e615d83a0b53b6a6dfde713d7e414c

**Comment by subsoap** [comment] 2020-03-10 06:37
I for sure was still seeing crashes happen due to this in February.

**Comment by AGulev** [comment] 2020-03-10 16:56
@subsoap do you mean you were able to reproduce them in Feb?

**Comment by subsoap** [comment] 2020-03-11 18:44
@AGulev I must have mixed up date periods. Looking at commit dates it looks like my iap_manager project already had the broadcast workarounds in place before February, and I know it wasn't crashing after that. I was working on an IAP project that month but I can't remember if I tested a stand alone project so... if it doesn't crash with a msg.post to nowhere in the callback now then it probably is fixed.

**Comment by britzl** [comment] 2020-03-12 10:15
I'm closing the issue. Reopen if it turns out that it still happens.

**Closed by britzl** 2020-03-12 10:15 UTC
Labels: bug, moreinfo
